'use server';

import { createClient } from '@/lib/supabase/server';
import { startOfWeek, endOfWeek, format } from 'date-fns';
import { getSummaryMetrics } from './summary';

export async function generateMarkdownExport(date: Date) {
    const supabase = await createClient();
    const start = startOfWeek(date, { weekStartsOn: 1 });
    const end = endOfWeek(date, { weekStartsOn: 1 });
    const weekStartStr = format(start, 'yyyy-MM-dd');
    const weekEndStr = format(end, 'yyyy-MM-dd');

    // Fetch Metrics
    const metrics = await getSummaryMetrics(date);

    // Fetch AI Summary
    const { data: summaryData } = await supabase
        .from('td_weekly_summaries')
        .select('summary_text')
        .eq('week_start', weekStartStr)
        .single();

    // Fetch Dailies
    const { data: dailies } = await supabase
        .from('td_dailies')
        .select('entry_date, content')
        .gte('entry_date', weekStartStr)
        .lte('entry_date', weekEndStr)
        .order('entry_date');

    // Fetch Tasks (Created this week)
    const { data: tasks } = await supabase
        .from('td_tasks')
        .select('title, completed, source, created_at')
        .gte('created_at', start.toISOString())
        .lte('created_at', end.toISOString())
        .order('created_at');

    // Build Markdown
    let md = `# TaskDaily Weekly Report\n`;
    md += `**Week:** ${weekStartStr} to ${weekEndStr}\n\n`;

    md += `## Weekly Metrics\n`;
    md += `- **Productivity Score:** ${metrics.productivity}%\n`;
    md += `- **Tasks Completed:** ${metrics.tasksCompleted}\n`;
    md += `- **Tasks Created:** ${metrics.tasksCreated}\n`;
    md += `- **Daily Entries:** ${metrics.dailyEntries}\n\n`;

    md += `## AI Summary\n`;
    md += `${summaryData?.summary_text || 'No AI summary generated.'}\n\n`;

    md += `## Daily Entries\n`;
    if (dailies && dailies.length > 0) {
        dailies.forEach((d: any) => {
            md += `### ${d.entry_date}\n${d.content || '(No content)'}\n\n`;
        });
    } else {
        md += `No daily entries found.\n\n`;
    }

    md += `## Tasks Log\n`;
    if (tasks && tasks.length > 0) {
        tasks.forEach((t: any) => {
            md += `- [${t.completed ? 'x' : ' '}] ${t.title} (${t.source})\n`;
        });
    } else {
        md += `No tasks created this week.\n\n`;
    }

    md += `\n---\nGenerated by TaskDaily on ${new Date().toLocaleString()}`;

    return md;
}
